### ISSUE TITLE
Increase python test coverage by extending --tiny_test for each use cases

### ISSUE THREAD

**Issue by akenmorris** [SCIInstitute/ShapeWorks#423] opened 2020-03-05 19:38 UTC
There are issues regarding needing a way to download only a subset.

**Comment by cchriste** [comment] 2020-06-22 16:17
Related issue #595

**Comment by sheryjoe** [comment] 2021-02-15 18:18
@akenmorris is this still an issue?

**Comment by akenmorris** [comment] 2021-02-15 20:02
I think it's probably still a good idea.  I believe we have the subset download working, thought this will add a dependency to the data portal for all Github actions (e.g. if the portal is down, no branches will build).  There is also the question of authentication.  Right now, the python script will drop to a console prompt asking for a username and password.

**Comment by sheryjoe** [comment] 2021-02-16 01:43
Related to #611

**Comment by cchriste** [comment] 2021-05-19 21:17
closing as duplicate of #611

**Closed by cchriste** 2021-05-19 21:17 UTC
