### ISSUE TITLE
Problem with writing image to array and back

### ISSUE THREAD

**Issue by jadie1** [SCIInstitute/ShapeWorks#895] opened 2021-01-13 19:19 UTC
When this is run:
```
import shapeworks as sw
shapeSeg1 = sw.Image(segmentation.nrrd)
shapeSeg_array = shapeSeg1.toArray()
shapeSeg2 = sw.Image(shapeSeg_array)
shapeSeg2.setSpacing(shapeSeg1.spacing())
shapeSeg2.setOrigin(shapeSeg1.origin())
```
Then `shapeSeg1.compare(shapeSeg2)` should be `True` but it is `False`. 

Here is an example:
shapeSeg1 
![image](https://user-images.githubusercontent.com/54382613/104498853-79fe5380-5599-11eb-928c-3c9d07f4c1f6.png)
shapeSeg2
![image](https://user-images.githubusercontent.com/54382613/104498883-82568e80-5599-11eb-875d-7e4d8efab521.png)

**Comment by cchriste** [comment] 2021-01-21 01:20
Tangentially related to #903, which would make this unnecessary for some workflows.

**Comment by cchriste** [comment] 2021-05-19 20:54
Duplicate of #965, which coincidentally is now fixed.

**Comment by cchriste** [comment] 2021-05-19 20:55
Used to be: <img width="1596" alt="incorrect_initialized_from_array_from_correct" src="https://user-images.githubusercontent.com/1260945/118883147-29ce2f80-b8b2-11eb-9617-94a724c7d196.png">
<img width="1596" alt="correct" src="https://user-images.githubusercontent.com/1260945/118883138-26d33f00-b8b2-11eb-8809-52b61e903088.png">

**Closed by cchriste** 2021-05-19 20:54 UTC
Labels: bug
