### ISSUE TITLE
[Python] when chaining calls using Image function's bound to Python using C++ lambdas, the image is not modified after the first call (fixed in pybind branch)

### ISSUE THREAD

**Issue by sheryjoe** [SCIInstitute/ShapeWorks#861] opened 2020-12-13 18:14 UTC

**Comment by cchriste** [comment] 2020-12-14 21:46
Can we add an example of this not working? In one of the Jupyter notebooks this line suggests an issue, but it's not clear since the commented line is identical to what is used:
```python
# here we will perform antialias-translate-binarize by chaining the apis
#shapeSegCentered.antialias(antialias_iterations).translate(translationVector).binarize()
shapeSegCentered.antialias(antialias_iterations).translate(translationVector).binarize()
```
Does it only happen when it's in the middle of a chain or at the end?

**Comment by sheryjoe** [comment] 2020-12-15 19:52
This works 
shapeSeg.antialias().resample([1,1,1])
shapeSeg.binarize()

This does not work
shapeSeg.antialias().resample([1,1,1]).binarize()

**Comment by archanasri** [comment] 2021-01-13 20:36
After some debugging, it looks like resample() is the problem. When chaining resample() with pad() does not work. So this is also related to #831 .

**Comment by cchriste** [comment] 2021-01-14 22:12
The problem is chaining functions created using lambdas. pybind11's automatic method of binding functions works, so we need to figure out what they do.

**Comment by cchriste** [comment] 2021-01-14 22:33
Note: here is evidence that non-lambda bindings are working and lambda bindings are not:
```
img.setSpacingLambda([0.2,0.2,1]).setSpacingLambda([2,2,0.2])
Out[9]:
{
	dims: [100, 98, 98],
	origin: [0, 0.5, 0.5],
	size: [200, 196, 19.6],
	spacing: [2, 2, 0.2]
}
In [10]:

print(img)
{
	dims: [100, 98, 98],
	origin: [0, 0.5, 0.5],
	size: [20, 19.6, 98],
	spacing: [0.2, 0.2, 1]
}
In [12]:

img.setSpacing(sw.Vector(0.2,0.2,1)).setSpacing(sw.Vector(2,2,0.2))
Out[12]:
{
	dims: [100, 98, 98],
	origin: [0, 0.5, 0.5],
	size: [200, 196, 19.6],
	spacing: [2, 2, 0.2]
}
In [13]:

print(img)
{
	dims: [100, 98, 98],
	origin: [0, 0.5, 0.5],
	size: [200, 196, 19.6],
	spacing: [2, 2, 0.2]
}
```

**Comment by cchriste** [comment] 2021-01-15 17:34
All chaining is now fixed. Will send a pull request soon.
The problem was that lambda functions without explicit return type use deduction of function's return type, and deduction automatically converts references to copies. 
```
Image& foo() { return *this }
(Image& img) { return img.foo; }  // return Image, not Image&
(Image& img) -> Image& { return img.foo; } // now it returns Image&  
(Image& img) -> decltype(auto) { return img.foo; } // returns Image& and easier to maintain (i.e., preferred method)
```

**Comment by cchriste** [comment] 2021-02-22 23:28
@sheryjoe @akenmorris How close are we to the 6.0 release? This would be trivial to add.

**Comment by archanasri** [comment] 2021-05-25 18:13
@sheryjoe yes, it needs to be merged to the master with the Pybind PR

**Closed** 2021-06-03 17:35 UTC
Labels: QA
