### ISSUE TITLE
Tests need to write to a directory outside source tree

### ISSUE THREAD

**Issue by cchriste** [SCIInstitute/ShapeWorks#1066] opened 2021-03-01 17:03 UTC
I know lots of our tests, and possibly our use cases, are writing output files to paths inside the source tree. This makes git status very cluttered and therefore likely to miss files that need committing. 

We could write to /tmp or the equivalent on Windows, and there may be more explicit wrt test cases, but let's do this and set defaults to locations outside the tree. 

I oppose the notion of adding every possible test output to .gitignore, especially since the outputs might be just about the same names as the inputs.

**Comment by akenmorris** [comment] 2021-03-01 17:08
Agreed!  Duplicate of #637

**Closed by akenmorris** 2021-03-01 17:08 UTC
