### ISSUE TITLE
Writing ASCII meshes

### ISSUE THREAD

**Issue by jadie1** [SCIInstitute/ShapeWorks#1514] opened 2021-10-19 16:03 UTC
Can we add the ability to write VTK meshes in ASCII format? This format is necessary for applications like CloudCompare and FEBio Studio.

**Comment by cchriste** [comment] 2021-10-19 21:05
Closing as duplicate of #1400. Please add tag to that issue for priority (high, med, low).

**Closed by cchriste** 2021-10-19 21:05 UTC
Labels: Feature Request
