### ISSUE TITLE
developer documentation (class diagram) - add instructions for automation

### ISSUE THREAD

**Issue by sheryjoe** [SCIInstitute/ShapeWorks#170] opened 2019-09-26 15:30 UTC

**Comment by cchriste** [comment] 2021-09-17 18:53
We want Doxygen output to be used by our documentation generator for a comprehensive, self-updating API Reference section (this issue may be a duplicate).

**Comment by cchriste** [comment] 2021-09-17 19:02
Closing this as duplicate of #1079.

**Closed by cchriste** 2021-09-17 19:02 UTC
Labels: Documentation
