### ISSUE TITLE
No test output should be written to source tree (treat it as read only)

### ISSUE THREAD

**Issue by 0leks** [SCIInstitute/ShapeWorks#637] opened 2020-07-22 04:09 UTC
Probably needs some clever .gitignore line.
Already caused Hong to commit bunch of Testing/data/*/output/ folders to his branch

**Comment by cchriste** [comment] 2020-07-22 20:22
For example, OptimizeTests currently outputs a bunch of stuff that clogs git.

This is as much for clarity during development as it is for ensuring our system works even when things are stored in a read only location (such as /Applications on OSX or many places on AWS, SCI servers, or other remote locations).

**Comment by akenmorris** [comment] 2021-03-01 17:09
Agree with the title of this issue and comments in #1066

**Comment by cchriste** [comment] 2021-06-23 16:31
closing as duplicate of #1066 and #1266

**Closed by cchriste** 2021-06-23 16:31 UTC
