### ISSUE TITLE
Generalize Image class to handle vector-valued voxels

### ISSUE THREAD

**Issue by sheryjoe** [SCIInstitute/ShapeWorks#1053] opened 2021-02-23 20:47 UTC
Related to:
#1012 
#1015

Example use cases:
- volumetric correspondences (e.g. diffusion images, multiple clinically-relevant metrics - cortical thickness, bone density ... etc) - related to Andy's project

**Comment by cchriste** [comment] 2021-03-02 17:39
The very limited skeleton of VectorImage that was just added has an "evaluate" function. Perhaps we should add a similar function to our current Image class to get the weighted scalar value of a given location in space.

**Comment by cchriste** [comment] 2021-10-12 23:39
Closing as duplicate of #1080.

**Comment by cchriste** [comment] 2022-01-25 20:02
Is this a duplicate of #1080? If not, can we be more specific about what is being requested? Thanks!

**Comment by akenmorris** [comment] 2022-01-25 20:19
Duplicate of #1080

**Closed by akenmorris** 2022-01-25 20:19 UTC
Labels: wontfix, Low Priority, Consolidation
