### ISSUE TITLE
Prep/Groom Tools consolidate into library

### ISSUE THREAD

**Issue by akenmorris** [SCIInstitute/ShapeWorks#209] opened 2019-10-09 04:58 UTC
Prep/Groom tools should be consolidated into a library that command line tools, python and Studio can use.

**Comment by akenmorris** [comment] 2020-03-06 00:22
@cchriste, @sheryjoe  Is a singular groom/prep library still being planned?  Instead I see new libraries for Image, Mesh, Alignment, etc. 

If it is no longer planned, please close this issue.

**Comment by cchriste** [comment] 2020-03-07 05:18
We are on the right track with consolidation into a library with multiple classes. This issue is a duplicate of the general consolidation task and can be closed.

**Closed by cchriste** 2020-03-07 05:18 UTC
